[package]
name = "brotli-no-stdlib"
version = "1.0.5"
authors = ["Daniel Reiter Horn <danielrh@dropbox.com>", "The Brotli Authors"]
description = "A brotli decompressor that does not use the rust stdlib. This makes it suitable for embedded devices and kernels. It is designed with a pluggable allocator so that the standard lib's allocator may be employed. For users wishing to use the stdlib, the brotli package, which calls into and abstracts this package, is recommended."
license = "BSD-3-Clause/MIT"
documentation = "https://github.com/google/brotli/tree/master/docs"
homepage = "https://github.com/dropbox/rust-brotli-no-stdlib"
repository = "https://github.com/dropbox/rust-brotli-no-stdlib"
keywords = ["brotli", "decompression", "lz77", "huffman", "nostd"]
readme = "README.md"

[[bin]]
doc = false
name = "brot"

[dependencies]
"alloc-no-stdlib" = "~1.2"

[features]
unsafe = []
disable-timer = []